### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by Poussinou** [qbait/CheckitTravelKit#1]
Hi,

What is the license of this project? If you haven't already choose, I would suggest GNU GPL v3.

The goal of this question is to know if we should have a look at this app to include it in [F-Droid](https://f-droid.org/), if you're ok with that.

**Comment by qbait** [comment]
I've just added the license @Poussinou and I'm fine with being included in F-Droid, thank you.

**Comment by Poussinou** [comment]
Thanks :)

**Comment by Poussinou** [comment]
Hum, Crashlytics and Firebase are closed libraries. Does the app work without firebase?
